replicaCount: 1
image:
  tag: "dev-eks-446f99f"
ingress:
  enabled: true
  className: alb
  host: dev-eks.namiview.com
  annotations:
    alb.ingress.kubernetes.io/group.name: eks-namiview
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
vault:
  clusterSecretStore: aws-secrets-manager
  refreshInterval: "1h"
  paths:
    dockerReg: namiview-prod/dockerhub
autoscaling:
  enabled: false
