apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namiview-ui
  namespace: argocd
spec:
  project: namiview
  source:
    repoURL: https://github.com/Darbuki/namiviewk8s.git
    targetRevision: 69-set-up-namiview-on-aws
    path: apps-eks/namiview-ui
  destination:
    server: https://kubernetes.default.svc
    namespace: namiview
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
