apiVersion: v1
kind: Service
metadata:
  name: namiview-service
  namespace: namiview-app
spec:
  selector:
    app: namiview-app
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP