apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: namiview
  source:
    repoURL: https://github.com/Darbuki/namiviewk8s.git
    targetRevision: 103-hybrid-homelab-aws-move-compute-from-eks-to-homelab
    path: infrastructure-homelab/cloudflare
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
