apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault
resources:
  - cluster-store.yaml
  - cluster-ops-rolebinding.yaml
helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.32.0
    releaseName: vault
    valuesFile: values.yaml
