server:
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      setNodeId: true
      config: |
        ui = true

        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"

          telemetry {
            unauthenticated_metrics_access = true
            disable_hostname = true
            prometheus_retention_time = "12h"
          }
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

        telemetry {
          prometheus_retention_time = "12h"
          disable_hostname         = true
        }

  dataStorage:
    enabled: true
    size: 3Gi

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - vault
          topologyKey: "kubernetes.io/hostname"

serverTelemetry:
  prometheusOperator: true
telemetry:
  prometheusRetentionTime: "12h"
  disableHostname: true
  unauthenticatedMetricsAccess: true