apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: namiview
  source:
    repoURL: https://github.com/Darbuki/namiviewk8s.git
    targetRevision: 69-set-up-namiview-on-aws
    path: infrastructure-eks/arc-controller
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
