apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: namiview
  source:
    repoURL: https://github.com/Darbuki/namiviewk8s.git
    targetRevision: 69-set-up-namiview-on-aws
    path: infrastructure-eks/eso-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
