apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: namiview
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 13.5.0
      helm:
        valueFiles:
          - $values/infrastructure-eks/loki/values.yaml
    - repoURL: https://github.com/Darbuki/namiviewk8s.git
      targetRevision: 88-bootstrap-dev-environment-in-eks-cluster-shape-2
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
