{
 "title": "namiview dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namiview_environment",
    "query": "prod : namiview-app, dev : namiview-dev"
   }
  ]
 },
 "panels": [
  {
   "title": "Namiview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unique Users",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max by (namespace) (namiview_unique_users{namespace=~\"$namiview_environment\"}))"
      }
     ]
    },
    {
     "title": "Gallery Images",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(max by (namespace) (namiview_gallery_images{namespace=~\"$namiview_environment\"}))"
      }
     ]
    },
    {
     "title": "Images Uploaded (24h)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(namiview_images_uploaded_total{namespace=~\"$namiview_environment\"}[24h]))"
      }
     ]
    },
    {
     "title": "Images Saved (24h)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 13, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(namiview_images_saved_total{namespace=~\"$namiview_environment\"}[24h]))"
      }
     ]
    },
    {
     "title": "API Pod Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=~\"$namiview_environment\", container=\"app\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "API Pod CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namiview_environment\", container=\"app\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "User Activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(namiview_logins_total{namespace=~\"$namiview_environment\"}[$__rate_interval]))",
       "legendFormat": "Logins"
      },
      {
       "expr": "sum(rate(namiview_metadata_edits_total{namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "Metadata Edits"
      }
     ]
    },
    {
     "title": "Network I/O (by pod)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (pod) (rate(container_network_receive_bytes_total{namespace=~\"$namiview_environment\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} rx"
      },
      {
       "expr": "sum by (pod) (rate(container_network_transmit_bytes_total{namespace=~\"$namiview_environment\"}[$__rate_interval]))",
       "legendFormat": "{{pod}} tx"
      }
     ]
    },
    {
     "title": "Pod Restarts",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 160 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (namespace) (kube_pod_container_status_restarts_total{namespace=~\"$namiview_environment\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "minio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Health Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_cluster_health_status{job=~\"minio\"}",
       "legendFormat": "Pool: {{pool}} Set: {{set}}"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\"minio\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"minio\"}) by (instance))",
       "legendFormat": "Used"
      },
      {
       "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"minio\"}) by (instance)) ",
       "legendFormat": "Free"
      }
     ]
    },
    {
     "title": "Number of Objects",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 9, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(minio_cluster_usage_object_total{job=~\"minio\"})"
      }
     ]
    },
    {
     "title": "Number of Buckets",
     "type": "stat",
     "gridPos": { "h": 6, "w": 5, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(minio_cluster_bucket_total{job=~\"minio\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(minio_node_process_cpu_total_seconds{job=~\"minio\"}[$__rate_interval])",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Memory Usage ",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "minio_node_process_resident_memory_bytes{job=~\"minio\"}",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Total S3 Ingress",
     "type": "stat",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=~\"minio\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Total S3 Egress",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 9, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=~\"minio\"})"
      }
     ]
    },
    {
     "title": "S3 API Request Error Rate (4xx)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (server,api) (increase(minio_s3_requests_4xx_errors_total{job=~\"minio\"}[$__rate_interval]))",
       "legendFormat": "{{server,api}}"
      }
     ]
    },
    {
     "title": "S3 API Egress Rate ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{job=~\"minio\"}[$__rate_interval]))",
       "legendFormat": "Data Sent [{{server}}]"
      }
     ]
    },
    {
     "title": "S3 API Ingress Rate ",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 9, "x": 10, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{job=~\"minio\"}[$__rate_interval]))",
       "legendFormat": "Data Received [{{server}}]"
      }
     ]
    },
    {
     "title": "Read, Write I/O",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(minio_node_io_rchar_bytes{job=~\"minio\"}[$__rate_interval])",
       "legendFormat": "Node RChar [{{server}}]"
      },
      {
       "expr": "rate(minio_node_io_wchar_bytes{job=~\"minio\"}[$__rate_interval])",
       "legendFormat": "Node WChar [{{server}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Vault status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vault health status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "up{job=\"vault\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Sealed Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "max(1 + vault_core_unsealed{})", "legendFormat": "{{ instance }}" }
     ]
    },
    {
     "title": "vault secret count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vault_secret_kv_count", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "ArgoCD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repositories",
     "type": "stat",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count by (repo) (argocd_app_info{namespace=~\"argocd\"}))"
      }
     ]
    },
    {
     "title": "Sync Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 9, "y": 297 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace=~\"argocd\",dest_server!=\"\",health_status!=\"\",sync_status!=\"\",health_status!=\"\"}) by (sync_status)",
       "legendFormat": "{{sync_status}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 6, "w": 1, "x": 23, "y": 297 },
     "options": {
      "content": "![argoimage](https://avatars1.githubusercontent.com/u/30269780?s=110&v=4)"
     }
    },
    {
     "title": "Health Status",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 304 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(argocd_app_info{namespace!=\"\",dest_server!=\"\",health_status!=\"\",sync_status!=\"\",health_status!=\"\"}) by (health_status)",
       "legendFormat": "{{health_status}}"
      }
     ]
    },
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 9, "y": 304 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_alloc_bytes{job=\"argocd-metrics\",namespace=~\"argocd\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 310 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"argocd-metrics\",namespace=~\"argocd\"}[1m])",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  }
 ]
}