apiVersion: apps/v1
kind: Deployment
metadata:
  name: namiview-app
  namespace: namiview-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: namiview-app
  template:
    metadata:
      labels:
        app: namiview-app
    spec:
      imagePullSecrets:
        - name: namiview-dockercfg-secret
      containers:
        - name: app
          image: darbuki/namiview:01-02
          ports:
            - containerPort: 8501
          env:
            - name: MINIO_ENDPOINT
              value: "minio.namiview-infra.svc.cluster.local:9000"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: namiview-connection-secret
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: namiview-connection-secret
                  key: MONGO_PASSWORD
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: namiview-connection-secret
                  key: MONGO_DB
            - name: MONGO_URI
              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo-mongodb-0.mongo-mongodb-headless.namiview-infra.svc.cluster.local:27017,mongo-mongodb-1.mongo-mongodb-headless.namiview-infra.svc.cluster.local:27017,mongo-mongodb-2.mongo-mongodb-headless.namiview-infra.svc.cluster.local:27017/namiview?replicaSet=rs0&authSource=admin"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: namiview-connection-secret
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: namiview-connection-secret
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: namiview-connection-secret
                  key: MINIO_BUCKET
            - name: MINIO_SECURE
              valueFrom:
                secretKeyRef:
                  name: namiview-connection-secret
                  key: MINIO_SECURE
            - name: GOOGLE_REDIRECT_URI
              value: "https://namiview.com"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/google_credentials.json"
          volumeMounts:
            - name: google-creds
              mountPath: "/app/google_credentials.json"
              subPath: "google_credentials.json"
              readOnly: true
      volumes:
        - name: google-creds
          secret:
            secretName: namiview-google-creds-external-secret
            items:
              - key: "google-creds.json"
                path: "google_credentials.json"