apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: namiview-docker-creds
  namespace: namiview-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: namiview-dockercfg-secret
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: namiview/app/docker-reg
        property: .dockerconfigjson