apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: namiview-connection-secret
  namespace: namiview-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: namiview-connection-secret
  data:
    - secretKey: MONGO_USER
      remoteRef:
        key: namiview/infra/mongodb/root
        property: username
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: namiview/infra/mongodb/root
        property: password
    - secretKey: MONGO_DB
      remoteRef:
        key: namiview/infra/mongodb/db
        property: name
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: namiview/infra/minio/root
        property: rootUser
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: namiview/infra/minio/root
        property: rootPassword
    - secretKey: MINIO_BUCKET
      remoteRef:
        key: namiview/infra/minio/bucket
        property: name
    - secretKey: MINIO_SECURE
      remoteRef:
        key: namiview/infra/minio/secure
        property: value

