apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: namiview-google-creds-external-secret
  namespace: namiview-app
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-backend # Use a CLUSTER secret store
    kind: ClusterSecretStore
  target:
    name: namiview-google-creds-external-secret
  data:
    - secretKey: GOOGLE_APPLICATION_CREDENTIALS
      remoteRef:
        key: namiview/app/google_credentials.json
  