apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: namiview-google-creds-external-secret
  namespace: namiview-app
spec:
spec:
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  data:
    - secretKey: google-creds.json
      remoteRef:
        key: namiview/app/google_creds.json
        property: google_creds.json