---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - cloudflare
  selector:
    matchLabels:
      app: cloudflared
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
