---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - namiview-infra
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  endpoints:
    - port: tcp-api
      interval: 30s
      path: /minio/v2/metrics/cluster
