---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - namiview-infra
  selector:
    matchLabels:
      app.kubernetes.io/name: mongodb
      app.kubernetes.io/component: metrics
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
