apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-operator-token
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: grafana-operator-token
  data:
    - secretKey: SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: grafana/api-key
        property: SERVICE_ACCOUNT_TOKEN
