apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - external-secret.yaml
  - grafana-instance.yaml
  - dashboards/namiview-api.yaml

helmCharts:
  - name: grafana-operator
    releaseName: grafana-operator
    version: v5.22.2
    repo: oci://ghcr.io/grafana/helm-charts
    includeCRDs: true
    valuesFile: values.yaml
