replicaCount: 2
image:
  repository: 015301735477.dkr.ecr.eu-west-1.amazonaws.com/namiview-ui
  tag: "eks-1854c1c"
ingress:
  enabled: true
  className: alb
  host: eks.namiview.com
  annotations:
    alb.ingress.kubernetes.io/group.name: eks-namiview
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
vault:
  clusterSecretStore: aws-secrets-manager
  refreshInterval: "1h"
  paths: {}
autoscaling:
  enabled: true
