apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-server-tls
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: grafana-server-tls
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: cloudflare/ssl-certificate
      property: tls.crt
  - secretKey: tls.key
    remoteRef:
      key: cloudflare/ssl-certificate
      property: tls.key