prometheus:
  prometheusSpec:
    retention: 5d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
    resources:
      requests:
        cpu: 60m
        memory: 256Mi
      limits:
        memory: 512Mi
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  admin:
    existingSecret: grafana-admin-secret
    userKey: admin-user
    passwordKey: admin-password

  initChownData:
    enabled: false

  podSecurityContext:
    fsGroup: 472
    runAsUser: 472

  containerSecurityContext:
    runAsUser: 472
    runAsGroup: 472
    runAsNonRoot: true

  grafana.ini:
    server:
      protocol: https
      http_port: 443
      cert_file: /etc/grafana/certs/tls.crt
      cert_key: /etc/grafana/certs/tls.key
  
  extraSecretMounts:
    - name: grafana-tls-certs
      secretName: grafana-server-tls
      mountPath: /etc/grafana/certs
      readOnly: true

  livenessProbe:
      httpGet:
        scheme: HTTPS
        port: 443
  readinessProbe:
      httpGet:
        scheme: HTTPS
        port: 443
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
  defaultDashboardsEnabled: true
  defaultDashboardsTimezone: utc
  service:
    type: ClusterIP
    port: 443
    targetPort: 443

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 15m
        memory: 48Mi
      limits:
        memory: 96Mi

nodeExporter:
  enabled: true

prometheus-node-exporter:
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      memory: 48Mi
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

kubeStateMetrics:
  enabled: true

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 15m
      memory: 48Mi
    limits:
      memory: 96Mi

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false