apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: namiview-infra
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:7.0
          # This command is MANDATORY for the replica set to function
          command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_USER
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_PASSWORD
            - name: MONGODB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_DB
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: mongo-nfs-storage