apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: google-json-sync
  namespace: namiview-app
spec:
  vaultAuthRef: namiview-auth
  mount: kv
  path: gcp\google_credentials.json
  type: kv-v2
  refreshAfter: 1h
  destination:
    name: google-creds-k8s-secret
    create: true