apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token-secret
  namespace: cloudflare
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
  data:
    - secretKey: CLOUDFLARE_TOKEN
      remoteRef:
        key: cloudflare/namiview-cloudflare-tunnel-token
        property: value


eyJhIjoiYzY3Y2FiNTMxNDhjNzhkYmEwZGRiMmYyMGUwMDQyOWIiLCJ0IjoiMzgwYzYwMTMtZTU2Yi00ZmExLWEwY2ItNjIxNjIyNmY1ZWFmIiwicyI6Ik5UY3dPVFF4TXpNdE5ERmxZUzAwTWpWaExXSTVNRFl0WTJZM09UTmlPREl6T1dGayJ9