apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-auth-secret
  namespace: namiview-infra
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: minio-auth-secret
  data:
    - secretKey: minio-root-user
      remoteRef:
        key: namiview/infra/minio/root
        property: rootUser
    - secretKey: minio-root-password
      remoteRef:
        key: namiview/infra/minio/root
        property: rootPassword