apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: namiview-infra
resources:
  - external-secret.yaml
  - external-tls-secret.yaml
helmCharts:
  - name: minio
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 17.0.21
    releaseName: minio
    valuesFile: values.yaml