apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vault-nfs-storage
  nfs:
    path: /srv/nfs/vault
    server: 192.168.1.127