apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arc-runners

resources:
  - external-secret.yaml
  - rbac.yaml

helmCharts:
  - name: gha-runner-scale-set
    releaseName: arc-cluster-ops
    version: 0.14.0
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    valuesFile: values.yaml
