apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runner-set
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:darbuki/namiviewk8s.git
    targetRevision: 54-set-up-self-hosted-github-actions-runner-on-cluster
    path: infrastructure/arc-runner-set
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
