apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts
      chart: minio
      targetRevision: 17.0.21
      helm:
        valueFiles:
          - $values/infrastructure/minio/values.yaml
    - repoURL: git@github.com:darbuki/namiviewk8s.git
      targetRevision: argo_deployment
      ref: values
    - repoURL: git@github.com:darbuki/namiviewk8s.git
      path: infrastructure/minio
      targetRevision: argo_deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: namiview-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    