apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namiview-dev-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/Darbuki/namiview-charts.git
    targetRevision: 26-decouple-ui-from-compute-react-fastapi-split
    path: charts/namiview-api
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: namiview-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
