apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arc-github-token
  namespace: arc-runners
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: arc-github-token
  data:
    - secretKey: github_token
      remoteRef:
        key: namiview/github/runners-pat
        property: value
