apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atlas-api-credentials
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: atlas-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: public_key
      remoteRef:
        key: namiview-prod/atlas-api-credentials
        property: public_key
    - secretKey: private_key
      remoteRef:
        key: namiview-prod/atlas-api-credentials
        property: private_key
    - secretKey: project_id
      remoteRef:
        key: namiview-prod/atlas-api-credentials
        property: project_id
