apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongo-auth-secret
  namespace: namiview-infra
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-cluster-gateway
    kind: ClusterSecretStore
  target:
    name: mongo-auth-secret
  data:
    - secretKey: mongodb-root-password
      remoteRef:
        key: namiview/infra/mongo/root
        property: password
    - secretKey: mongodb-replica-set-key
      remoteRef:
        key: namiview/infra/mongo/replica-set-key
        property: key